### PR TITLE
Add challenge 001 in Go

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by marceloboeira** [comment]
why do you have the pull-requests?

**Comment by ghost** [comment]
Sorry, I had forgotten how to merge a remote repository

**Comment by marceloboeira** [comment]
@gabrielalmir10 don't worry, just remember to always `git pull --rebase` instead of merging.

**Comment by ghost** [comment]
@marceloboeira thanks bro :smile:

**Pull request merged**
